### ISSUE TITLE
Stuck in Activating

### ISSUE THREAD

**Issue by githubpsyche** [leo-holanda/changes-counter#1]
I use Windows, both the regular and Insiders edition. Extension and app are up to date.

When I open VSCode without opening a specific folder, the output panel for the Changes Counter extension will say "The extension couldn't find a folder in your workspace. Open a folder that has git initialized for the extension to work." That's great.

But when I open a folder with git initialized, nothing appears in the output panel. Nothing appears in my status bar that refers to the extension and there is no apparent change tracking. The extension is installed, and I can configure its two settings, but nothing actually happens.

I can open a menu called "Running Extensions" from the extensions sidebar. It indicates that the extension is stuck "Activating...". I don't really know of any way to dig deeper than that.

**Comment by leo-holanda** [comment]
Thank you for opening the issue! :handshake: I'm working on it right now!

**Comment by leo-holanda** [comment]
I have managed to reproduce the bug in my machine and found what I think was the problem that is causing it. I have launched a new version with a patch for this bug. The version number is 1.2.2 and I think it is available to update now.

I have tried to reproduce the bug with this new version and I couldn't but please test it when you can and let me know if everything is working fine! I have noticed that the error messages in the output channel are insufficient and could be better so I'm launching soon a new version to improve this.

**Comment by githubpsyche** [comment]
it works for me now

Jordan
________________________________
