### ISSUE TITLE
status bar not updating

### ISSUE THREAD

**Issue by pixel-wraith** [leo-holanda/changes-counter#3]
After installing the extension, the status bar only shows `Changes: ?`. There is no output in the Panel. I'm assuming there are additional steps needed, but the documentation does not include anything regarding this.

Things I tried:
- restarting VS Code.
- switching to different files and file types
- adjusting the Settings
- pressing `CMD+SHIFT+P` > searching for "Counter" > setting a threshold value.w

**Comment by leo-holanda** [comment]
Hi @iamthe-Wraith! Thanks for opening this issue!

When `Changes: ?` appears, it usually means that a comparison branch hasn't been defined yet. The tooltip should appear like this:

![Screenshot from 2023-11-03 12-21-48](https://github.com/leo-holanda/changes-counter/assets/26936076/bf1a17bb-785e-4067-a632-c195b43737b0)

And the Output Channel like this:

![Screenshot from 2023-11-03 12-23-53](https://github.com/leo-holanda/changes-counter/assets/26936076/5a876ee1-463e-49e9-a9a6-91b4926f8e07)

Note that the "Changes Counter" option must be selected at the dropdown menu in the upper right.

Could you please verify if a comparison branch was defined? If it isn't defined, you can click at the "Set Comparison Branch" link at the tooltip or like you did press `CMD + SHIFT + P` and search for "Changes Counter: Set comparison branch". A input like this should appear:

![Screenshot from 2023-11-03 12-47-02](https://github.com/leo-holanda/changes-counter/assets/26936076/f5f59f16-b8e3-44ea-b1ca-056910fa52de)

Where clicking an option sets its branch as the comparison branch. Then, the tooltip should appear as this:

![Screenshot from 2023-11-03 12-48-58](https://github.com/leo-holanda/changes-counter/assets/26936076/a66110e5-c78e-424c-9a25-13ef0b54b414)


If trying these steps didn't work, please let me know!

**Comment by pixel-wraith** [comment]
@leo-holanda thank you for the information. I had not selected a comparison branch. My assumption was that it would default to whatever the default branch is for the project (I should not have assumed, this was my bad).

However, I am not getting a tooltip to appear when hovering/clicking on the `Changes: ?`. Instead, I am having to use `CMD+SHIFT+P` and search to find the `Change Counter: Set comparison branch` command. But after pressing Enter and when searching branches, I am not able to find all my branches in the search results. I've confirmed that I have pulled down everything from the remote, so all my branches *should* be showing up...but many are not.

I am seeing the output now...forgot to switch to the extension 🤣 😬 😅 

If a threshold and comparison branch must be set by the user, it might be a good idea to update your documentation with this information. 

Also, an optimization suggestion to make this easier on your users could be to default your comparison branch to the current branch's base branch. It's not always the same branch the user will be merging back into, but it's at least common enough, it could be a reasonable default).

**Comment by leo-holanda** [comment]
@iamthe-Wraith That's ok!! I should have thought more about this scenario. Using a default branch and better documentation could prevent this from happening. Thanks for suggesting this! I'm going to push some commits including them! 🤝

And the missing tooltip is strange 🤔 I'm trying to think about what is causing it. About the missing branches, could I ask how many branches do you have in this repository? Is it something like 100+ or 500+? I haven't tested it with repositories with that much of branches, actually. It could be something about the quantity.

**Comment by pixel-wraith** [comment]
Yeah, I'm not sure about the tooltip either. There is nothing in the output to indicate what might be going on with it.

For the branches, the team has 500+ so it very well could be a quantity issue.

**Comment by leo-holanda** [comment]
Hey @iamthe-Wraith! I published a new version, 1.5.0, with some fixes that might solve this missing branches problem. I have tested with the vscode repository that has 700+ branches and it worked fine. But please, test in your repository and let me know!

I'm still investigating why the tooltip might be disappearing but the comparison branch and changes threshold now have default values when a repository is opened for the first time. A great improvement so thanks for the idea again!

**Comment by pixel-wraith** [comment]
Awesome, thanks @leo-holanda!!! I'll try to test it out this week 😄

**Comment by pixel-wraith** [comment]
@leo-holanda sorry it's taken me a little bit to get back to you. Your update has resolved the branch issue! 🎉

For the tooltip, I'm now seeing it flash open and then immediately closing. It's happening really fast...it's only open for maybe 100-200 milliseconds. but since that is not relevant to this issue, I'll open a new one 😄 I think we're good on this issue!

Nice work on this!

**Comment by leo-holanda** [comment]
No problem, @iamthe-Wraith! I'm glad the update solved this bug, thanks again for letting me know about it!

Let's continue on the another issue
