### ISSUE TITLE
Allow Users to also list the 'Insertions' and 'Deletions' in the status bar?

### ISSUE THREAD

**Issue by Dylansc22** [leo-holanda/changes-counter#5]
I suppose this would be a feature request, but is there anyway to allow users to list not just the total 'Changes' in the status bar, but also the 'Insertions' and 'Deletions'. Perhaps a setting, that enables us to toggle each of them `true/false` to display in the bottom(?). It seems the only way to view that information is to hover for several seconds over the 'Changes'. 

It would be quite great if I could have an eye on all three values. Thanks again!

**Comment by leo-holanda** [comment]
Hi @Dylansc22! Yes, this is possible! Thanks for creating the issue. I have launched a new version that creates two settings to toggle the insertions and deletions data on the status item. Please, update the extension and tell me what you think.

I was afraid that the status bar item would be too long if I used the full words so I just used Ins and Del.

**Comment by Dylansc22** [comment]
So great and wow! Thanks for getting back to this so quickly @leo-holanda! I often have to refactor my codebase and I'm trying to pare it down for simplicity -- its a nice little reminder to see how much code I'm adding/removing as I make my commits. 

Only other suggestion would be to adjust the spacing/padding between each of the three stats, and (highly preferable) add boldness and color to the stats (see screenshot). At least for me, those tweaks would make it more useful at a quick glance =]. Thank you again for this cool little extension!

<img width="636" alt="image" src="https://github.com/leo-holanda/changes-counter/assets/7850929/c8623849-5702-47fd-91bf-295ec5012d18">

**Comment by leo-holanda** [comment]
You're welcome, @Dylansc22! It's a pleasure to help. It's great to see the extension being useful to you!

The suggestion you made would be a great improvement and I wish I could implement it but unfortunately VS Code gives no control regarding the font weight inside a status bar item :disappointed:. It is possible to change the font color but it changes the whole text instead of just the number. It would be possible to create multiple status bar items and separate the strings with them but another status bar item from another extension could get in the way and change the order which would look weird.

The spacing is possible, though. I launched a new version with the changes. Please, update the extension and tell me what you think.

**Comment by Dylansc22** [comment]
Ahh, unfortunate you can't have separate colors easily - having them show up in color would make them much easier to spot at a glance. 

I was trying to see if I could contribute and seeing if I could do it myself (but I've never worked with the VSCode Extensions API so I'm flying blind. I made it as far as the following changes to `status-bar-item.ts`, but was having little luck the below code isn't operational, but it was an attempt... Might try and give it another attempt eventually!

Regardless the changes you made are still a great improvement =]

```
import * as vscode from "vscode";
import { ChangesService } from "../changes/changes.service";
import { ChangesData } from "../changes/changes.interfaces";

export class StatusBarItem {
  private changesData?: ChangesData;
  private context!: vscode.ExtensionContext;
  private statusBarItem!: vscode.StatusBarItem;
  private changesService: ChangesService;

  private changesStatusBarItem!: vscode.StatusBarItem;
  private deletionsStatusBarItem!: vscode.StatusBarItem;
  private insertionsStatusBarItem!: vscode.StatusBarItem;

  private static instance: StatusBarItem;

  constructor(context: vscode.ExtensionContext) {
    this.context = context;
    this.changesService = new ChangesService(context);
  }

  static getInstance(context: vscode.ExtensionContext): StatusBarItem {
    if (!StatusBarItem.instance) StatusBarItem.instance = new StatusBarItem(context);
    return StatusBarItem.instance;
  }

  async init(): Promise<void> {
    this.changesStatusBarItem = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Left, 10);
    this.deletionsStatusBarItem = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Left, 9);
    this.insertionsStatusBarItem = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Left, 8);

    this.context.subscriptions.push(this.changesStatusBarItem);
    this.context.subscriptions.push(this.deletionsStatusBarItem);
    this.context.subscriptions.push(this.insertionsStatusBarItem);

    await this.updateStatusBarItemData();
    this.changesStatusBarItem.show();
    this.deletionsStatusBarItem.show();
    this.insertionsStatusBarItem.show();
  }

  async updateStatusBarItemData(): Promise<void> {
    await this.updateChangesData();
    this.updateText();
    this.updateColor();
    this.updateTooltip();
  }

  private async updateChangesData(): Promise<void> {
    this.changesData = await this.changesService.getChangesData();
  }

  private updateText(): void {
    const changesText = `Changes: ${this.changesData?.total || "?"}`;
    const insertionsText = ` Ins: ${this.changesData?.insertions || "?"}`;
    const deletionsText = ` Del: ${this.changesData?.deletions || "?"}`;

    this.changesStatusBarItem.text = changesText;
    this.insertionsStatusBarItem.text = insertionsText;
    this.deletionsStatusBarItem.text = deletionsText;
  }

  private shouldChangeColor(): boolean {
    const config = vscode.workspace.getConfiguration("changesCounter");
    const shouldDisableColorChange = config.get<boolean>("disableStatusBarIconColorChange");
    return !shouldDisableColorChange && (this.changesData?.hasExceededThreshold || false);
  }

  private updateColor(): void {
    if (this.shouldChangeColor()) {
      this.insertionsStatusBarItem.backgroundColor = new vscode.ThemeColor("statusBarItem.errorForeground");
      this.deletionsStatusBarItem.backgroundColor = new vscode.ThemeColor("statusBarItem.warningForeground");
    } else {
      this.insertionsStatusBarItem.backgroundColor = undefined;
      this.deletionsStatusBarItem.backgroundColor = undefined;
    }
  }

  private updateTooltip(): void {
    this.statusBarItem.tooltip = this.getTooltipString();
  }

  private getTooltipString(): vscode.MarkdownString {
    const markdownTooltip = new vscode.MarkdownString();

    this.appendChangesDataMarkdown(markdownTooltip);
    this.appendSettingsMarkdown(markdownTooltip);
    this.appendCommandsMarkdown(markdownTooltip);

    markdownTooltip.isTrusted = true;
    markdownTooltip.supportThemeIcons = true;
    markdownTooltip.supportHtml = true;

    return markdownTooltip;
  }

  private appendChangesDataMarkdown(markdownTooltip: vscode.MarkdownString): void {
    if (this.changesData) {
      markdownTooltip.appendMarkdown(
        `$(plus) <strong>Insertions: </strong> <span style="color:#3fb950;">${this.changesData.insertions}</span> <br>`
      );
      markdownTooltip.appendMarkdown(
        `$(remove) <strong>Deletions: </strong> <span style="color:#f85149;">${this.changesData.deletions}</span> <br>`
      );
      markdownTooltip.appendMarkdown(
        `$(chrome-maximize) <strong>Total Changes: </strong> ${this.changesData.total}<br>`
      );

      markdownTooltip.appendMarkdown("<hr>");
      markdownTooltip.appendMarkdown("<br>");
    }
  }

  private appendSettingsMarkdown(markdownTooltip: vscode.MarkdownString): void {
    const comparisonBranch = this.context.workspaceState.get<string>("comparisonBranch");
    const changesQuantityThreshold = this.context.workspaceState.get<string>(
      "changesQuantityThreshold"
    );

    if (comparisonBranch) {
      markdownTooltip.appendMarkdown(
        `$(git-branch) <strong>Current Comparison Branch</strong> <br> ${comparisonBranch}`
      );
    } else {
      markdownTooltip.appendMarkdown(
        `$(git-branch) <strong>Current Comparison Branch</strong> <br> Undefined`
      );
    }

    markdownTooltip.appendMarkdown("<br>");

    if (changesQuantityThreshold) {
      markdownTooltip.appendMarkdown(
        `$(arrow-both) <strong>Changes Quantity Threshold</strong> <br> ${changesQuantityThreshold} changes`
      );
    } else {
      markdownTooltip.appendMarkdown(
        `$(arrow-both) <strong>Changes Quantity Threshold</strong> <br> Undefined`
      );
    }

    markdownTooltip.appendMarkdown("<br>");

    if (!comparisonBranch) {
      markdownTooltip.appendMarkdown("<br>");
      markdownTooltip.appendMarkdown(`$(alert) Set the comparison branch.`);
    }

    if (!changesQuantityThreshold) {
      markdownTooltip.appendMarkdown("<br>");
      markdownTooltip.appendMarkdown(`$(alert) Set the changes quantity threshold.`);
    }
  }

  private appendCommandsMarkdown(markdownTooltip: vscode.MarkdownString): void {
    const comparisonBranch = this.context.workspaceState.get<string>("comparisonBranch");
    const changesQuantityThreshold = this.context.workspaceState.get<string>(
      "changesQuantityThreshold"
    );

    const setComparisonBranchCommandURI = vscode.Uri.parse(
      `command:changes-counter.setComparisonBranch`
    );
    const setChangesQuantityThresholdCommandURI = vscode.Uri.parse(
      `command:changes-counter.setChangesQuantityThreshold`
    );

    markdownTooltip.appendMarkdown(
      `<hr><br> $(edit) [${comparisonBranch ? "Change" : "Set"
      } Comparison Branch](${setComparisonBranchCommandURI}) <br>`
    );

    markdownTooltip.appendMarkdown(
      `$(edit) [${changesQuantityThreshold ? "Change" : "Set"
      } Changes Quantity Threshold](${setChangesQuantityThresholdCommandURI})`
    );
  }
}
```

**Comment by leo-holanda** [comment]
Hi @Dylansc22! Thanks for suggesting this code.

I have managed to fix what was making it not work. I have reached this result:

![Screenshot from 2024-02-26 10-20-36](https://github.com/leo-holanda/changes-counter/assets/26936076/63db0a44-8890-48fd-b4c8-9a22e5754559)

What do you think?

I thought better about the problem of having multiple items and the possibility that their order might change and look weird. Using the right priority numbers might make this unlikely to happen and if it happens then I might set some kind of configuration to toggle some sort of multi-item and single-item mode.

Edit: I published a new version now with these changes

**Comment by Dylansc22** [comment]
This is absolutely stellar! Exactly what I needed (such a good reminder to not write too much code before commiting) -- looks wonderful! Thank you!

**Comment by leo-holanda** [comment]
That's great to hear!! I'm glad that this solution could be reached. Thank you for creating this issue and if a bug appears or something like that please let me know!
